# -*- coding: utf-8 -*-
"""strachuk-dz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/0kni/480cd81f34e632619c797fbce6522c0f/strachuk-dz.ipynb
"""

!pip install requests pandas matplotlib seaborn -q
print("Библиотеки установлены")

from google.colab import files
import os

print("Загрузите файл логов Suricata (.json)")
uploaded = files.upload()

# Автоопределение JSON файла
log_files = [f for f in uploaded.keys() if f.endswith('.json')]
if log_files:
    LOG_FILE = log_files[0]
    print(f"Автовыбор: {LOG_FILE}")

    # Сохраняем
    with open(LOG_FILE, 'wb') as f:
        f.write(uploaded[LOG_FILE])
else:
    print("Нет .json! ")

# API-КЛЮЧ VIRUSTOTAL
VT_API_KEY = "21bdbb07866884603408d797726a433e3ae2e2ab615896d3f317f7d5abe32a04"
print(f"API ключ: {'Установлен' if VT_API_KEY else 'НЕ УСТАНОВЛЕН'}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from datetime import datetime
import os

# Файл уже определён
json_files = [f for f in os.listdir('.') if f.endswith('.json')]
LOG_FILE = json_files[0]
print(f" Анализ {LOG_FILE} ")
print("=" * 70)

# Читаем заново с правильной логикой
df = pd.read_json(LOG_FILE, lines=True)
print(f"Загружено: {len(df)} строк")

# ИЩЕМ IP точно (проверяем все варианты)
ip_mapping = {}
for col in df.columns:
    if 'ip' in col.lower():
        if 'src' in col.lower() or 'source' in col.lower():
            ip_mapping['src_ip'] = col
        elif 'dst' in col.lower() or 'dest' in col.lower():
            ip_mapping['dst_ip'] = col

print(" Найденные IP колонки:")
print(ip_mapping)

# Если не нашлось — берём первые колонки с 'ip'
if not ip_mapping:
    ip_cols = [col for col in df.columns if 'ip' in col.lower()]
    if ip_cols:
        ip_mapping['src_ip'] = ip_cols[0]  # первый найденный

src_ip_col = ip_mapping.get('src_ip')
if src_ip_col:
    print(f" Используем src_ip: '{src_ip_col}'")

    # Анализ событий по IP
    ip_counts = df[src_ip_col].value_counts().head(50)

    analysis_df = pd.DataFrame({
        'ip': ip_counts.index,
        'alert_count': ip_counts.values
    })

    print("\n ТОП IP:")
    print(analysis_df.head(10))

    # Простая классификация угроз (без VT пока)
    analysis_df['threat'] = analysis_df['alert_count'].apply(
        lambda x: 'HIGH' if x >= 10 else 'MEDIUM' if x >= 3 else 'LOW'
    )

    # =========================
    # ГРАФИК
    # =========================
    plt.figure(figsize=(12, 8))
    top10 = analysis_df.nlargest(10, 'alert_count')
    sns.barplot(data=top10, x='alert_count', y='ip', hue='threat', palette='Reds_r')
    plt.title(f' Топ-10 IP по активности ({LOG_FILE})')
    plt.xlabel('Количество событий')
    plt.tight_layout()
    plt.savefig('threat_chart.png', dpi=150, bbox_inches='tight')
    plt.show()

    # =========================
    # ОТЧЁТЫ
    # =========================
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    analysis_df.to_csv(f'threats_{timestamp}.csv', index=False)
    analysis_df.to_json(f'threats_{timestamp}.json', orient='records', indent=2)

    print(f"\n ФАЙЛЫ ГОТОВЫ:")
    print(f"    threats_{timestamp}.csv")
    print(f"    threats_{timestamp}.json")
    print(f"    threat_chart.png")